server:
  port: 8091
spring:
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://graywolf.top:6200/mobilepay_admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: mobilepay250715
  cloud:
    nacos:
      discovery:
        server-addr: graywolf.top:6202
        namespace: public
        username: nacos
        password: mobilepay250715
  redis:
    host: graywolf.top
    port: 6201
    password: mobilepay250715
  cache:
    type: redis

# 内部服务认证配置
app:
  internal:
    secret: mobilepay-internal-secret-2025
    # 是否启用内部服务认证（开发环境可设为false）
    enabled: false

# MyBatis Plus Configuration
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# Logging Configuration
logging:
  level:
    org.software.code: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# SpringDoc 相关配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  # 定义API分组，方便在网关聚合时区分
  group-configs:
    - group: 'admin'
      paths-to-match: '/**'
